---
- name: Perform apt update and upgrade on all hosts
  hosts: all
  become: true
  tasks:

    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600  # Only update if cache is older than 1 hour

    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: dist
