---
- name: Perform apt update and upgrade on all hosts
  hosts: all
  become: true  # << this is required for root access
  tasks:

    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: yes
