---
- name: Perform basic apt update and upgrade on all hosts
  hosts: all
  become: true  # 👈 This enables sudo
  tasks:

    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade installed packages
      ansible.builtin.apt:
        upgrade: yes
