---
- name: Configure static IP via Netplan (with /24 and resolv.conf)
  hosts: all
  become: true
  gather_facts: true

  vars:
    netplan_new_file: /etc/netplan/01-ansible-static.yaml
    dns_servers:
      - 10.101.0.5
    search_domain: raspinwall.com

  tasks:

    - name: Get primary network interface
      set_fact:
        primary_interface: "{{ ansible_default_ipv4.interface }}"

    - name: Get current IP address and gateway
      set_fact:
        static_ip: "{{ ansible_default_ipv4.address }}"
        gateway_ip: "{{ ansible_default_ipv4.gateway }}"
        netmask_cidr: "24"

    - name: Write static Netplan config file
      copy:
        dest: "{{ netplan_new_file }}"
        owner: root
        group: root
        mode: '0644'
        content: |
          network:
            version: 2
            ethernets:
              {{ primary_interface }}:
                dhcp4: no
                addresses:
                  - "{{ static_ip }}/{{ netmask_cidr }}"
                gateway4: "{{ gateway_ip }}"
                nameservers:
                  search: [{{ search_domain }}]
                  addresses:
                    - {{ dns_servers[0] }}
      notify: Apply new Netplan config

    - name: Overwrite /etc/resolv.conf with DNS and search domain
      copy:
        dest: /etc/resolv.conf
        content: |
          nameserver {{ dns_servers[0] }}
          search {{ search_domain }}
        owner: root
        group: root
        mode: '0644'

  handlers:
    - name: Apply new Netplan config
      command: netplan apply
