---
- name: Configure static IP via Netplan (non-destructive)
  hosts: all
  become: true
  gather_facts: true

  vars:
    netplan_new_file: /etc/netplan/01-ansible-static.yaml
    dns_servers:
      - 10.101.0.5

  tasks:
    - name: Get primary network interface
      set_fact:
        primary_interface: "{{ ansible_default_ipv4.interface }}"

    - name: Get current IP address, CIDR, and gateway
      set_fact:
        static_ip: "{{ ansible_default_ipv4.address }}"
        netmask_cidr: "{{ ansible_default_ipv4.network | ansible.utils.ipaddr('prefix') }}"
        gateway_ip: "{{ ansible_default_ipv4.gateway }}"

    - name: Write new static Netplan configuration
      template:
        src: netplan_static.j2
        dest: "{{ netplan_new_file }}"
        owner: root
        group: root
        mode: '0644'
      notify: Apply new Netplan config

  handlers:
    - name: Apply new Netplan config
      command: netplan apply
